<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lucca Frachelle, Cecilia Waksman">
<meta name="dcterms.date" content="2024-09-07">

<title>Entrega Final - Muestreo I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="muestreo_files/libs/clipboard/clipboard.min.js"></script>
<script src="muestreo_files/libs/quarto-html/quarto.js"></script>
<script src="muestreo_files/libs/quarto-html/popper.min.js"></script>
<script src="muestreo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="muestreo_files/libs/quarto-html/anchor.min.js"></script>
<link href="muestreo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="muestreo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="muestreo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="muestreo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="muestreo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Entrega Final - Muestreo I</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lucca Frachelle, Cecilia Waksman </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 7, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>El objetivo de este trabajo es seleccionar una muestra aleatoria de hogares de Montevideo bajo un diseño estratificado, por conglomerados y en dos etapas de selección. Los estratos son 5 y son definidos a nivel socioeconómico (1 = Bajo, 2 = Medio Bajo, 3 = Medio, 4 = Medio Alto, 5 = Alto). LA UPM es la manzana y la USM es el hogar.</p>
<p>Las UPM son seleccionadas bajo un diseño PPS sin reemplazo utilizando como medida de tamaño la cantidad de personas por UPM. Luego, dentro de cada UPM seleccionada en la primera etapa, se deben seleccionar 5 viviendas dentro de cada UPM con igual probabilidad de selección.</p>
<p>Una vez seleccionada la muestra, se computarán estimaciones puntuales para distintos parámetros (junto con medidas de calidad de las mismas). Las estimaciones para dichos parámetros pueden ser calculadas, ya sea, a nivel de toda la población, como para distintos dominios/áreas de estimación.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="parte-1" class="level2">
<h2 class="anchored" data-anchor-id="parte-1">Parte 1</h2>
<p>Calcule el tamaño de muestra para obtener un margen de error de <span class="math inline">\(\pm3\%\)</span> a un 95% de confianza para estimar cualquier proporción poblacional. Asuma un efecto de diseño de 1.5.</p>
<p><br>
</p>
<p>Paso 1) <span class="math inline">\(n_0=(\frac{z^*\sigma}{moe})^2 = (\frac{1.96 \times 0.5}{0.03})^2\)</span></p>
<p>Paso 2) <span class="math inline">\(n_1=\frac{n_0}{1+(n_0/N)}\)</span></p>
<p>Paso 3) <span class="math inline">\(n_{deff}=n_1 \times deff\)</span></p>
<p><br>
</p>
<p>El tamaño de muestra será entonces:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="fu">nrow</span>(df)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>z_star <span class="ot">=</span> <span class="fl">1.96</span>  </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>moe <span class="ot">=</span> <span class="fl">0.03</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>deff <span class="ot">=</span> <span class="fl">1.5</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>n0 <span class="ot">&lt;-</span> ((z_star <span class="sc">*</span> sigma) <span class="sc">/</span> moe)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> n0 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> (n0<span class="sc">/</span>N))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>neff <span class="ot">&lt;-</span> <span class="fu">round</span>(n1 <span class="sc">*</span> deff)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">as.data.frame</span>(neff))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  neff
1 1597</code></pre>
</div>
</div>
<p><br>
</p>
</section>
<section id="parte-2" class="level2">
<h2 class="anchored" data-anchor-id="parte-2">Parte 2</h2>
<p>Con el tamaño de muestra calculado en la parte anterior, asigne el mismo por estrato de forma óptima, utilizando como variable auxiliar el ingreso del hogar.</p>
<p>Tamaño de muestra por estrato según asignación óptima: <span class="math inline">\(n_h = n\times \frac{N_h sd_{U_h}[x]}{\sum_{h=1}^HN_h sd_{U_h}[x]}\)</span>, donde, <span class="math inline">\(x\propto y\)</span> aproximadamente, <em>x</em> es la variable auxiliar, <em>y</em> la variable de interés.</p>
<p><br>
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>estratos <span class="ot">=</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(estrato) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">N=</span><span class="fu">n</span>(),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">sd_ing_hog=</span><span class="fu">sd</span>(ingreso_hog))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>estratos <span class="ot">=</span> estratos <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">n_opt=</span><span class="fu">round</span>(neff<span class="sc">*</span>N<span class="sc">*</span>sd_ing_hog<span class="sc">/</span><span class="fu">sum</span>(N<span class="sc">*</span>sd_ing_hog)))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>estratos <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">estrato</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">sd_ing_hog</th>
<th style="text-align: right;">n_opt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">66632</td>
<td style="text-align: right;">901.0174</td>
<td style="text-align: right;">137</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">92165</td>
<td style="text-align: right;">1063.8405</td>
<td style="text-align: right;">223</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">124197</td>
<td style="text-align: right;">1328.8254</td>
<td style="text-align: right;">375</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">113171</td>
<td style="text-align: right;">1797.5697</td>
<td style="text-align: right;">463</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">56556</td>
<td style="text-align: right;">3108.8159</td>
<td style="text-align: right;">400</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br>
</p>
</section>
<section id="parte-3" class="level2">
<h2 class="anchored" data-anchor-id="parte-3">Parte 3</h2>
<p>En la primera etapa del muestreo por conglomerados, se selecciona una muestra de manzanas en cada estrato. El diseño utilizado es <span class="math inline">\(\pi ps\)</span> <em>sistemático</em> y las probabilidades de inclusión de cada manzana se calcula en función de su cantidad de personas que viven en la misma.</p>
<p>La cantidad de manzanas por estrato a seleccionar en la muestra se calcula como el tamaño de muestra por asigniación óptima respectivo (calculado en punto 2) dividido la cantidad de individuos a seleccionar en cada manzana en la segunda etapa, en este caso 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>U_upm<span class="ot">=</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"estrato"</span>, <span class="st">"manzana"</span>)))) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Mi=</span><span class="fu">sum</span>(cant_personas), <span class="at">.groups =</span> <span class="st">"keep"</span>, <span class="at">MOS=</span><span class="fu">n</span>())<span class="co">#cantidad de personas por manzana, cantidad de hogares por manzana</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># primera etapa</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>s_upm<span class="ot">=</span>sampling<span class="sc">::</span><span class="fu">strata</span>(<span class="at">data=</span>U_upm,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">stratanames =</span> <span class="st">"estrato"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">size=</span><span class="fu">round</span>(estratos<span class="sc">$</span>n_opt<span class="sc">/</span><span class="dv">5</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method=</span><span class="st">'systematic'</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">pik=</span>U_upm<span class="sc">$</span>Mi,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">description=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stratum 1 

Population total and number of selected units: 361 27 
Stratum 2 

Population total and number of selected units: 545 45 
Stratum 3 

Population total and number of selected units: 768 75 
Stratum 4 

Population total and number of selected units: 683 93 
Stratum 5 

Population total and number of selected units: 410 80 
Number of strata  5 
Total number of selected units 320 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selecciono neff/5 manzanas con el diseño PPS sistemático</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>s_upm <span class="ot">=</span> <span class="fu">getdata</span>(U_upm,s_upm) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">prob_upm=</span>Prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>En la segunda etapa, se seleccionan de cada manzana 5 hogares mediante un diseño aleatorio simple sin reposición con probabilidades de inclusión <span class="math inline">\(\frac{n_h}{N_h}\)</span>, según el estrato.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#segunda etapa</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>U_usm <span class="ot">=</span> df <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(s_upm <span class="sc">%&gt;%</span> <span class="fu">select</span>(manzana, prob_upm), <span class="at">by=</span><span class="st">"manzana"</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(prob_upm)<span class="sc">==</span><span class="cn">FALSE</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>U_usm<span class="ot">=</span> U_usm <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(manzana)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">5</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>s<span class="ot">=</span> sampling<span class="sc">::</span><span class="fu">strata</span>(<span class="at">data=</span>U_usm,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">stratanames =</span> <span class="st">'manzana'</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">size=</span><span class="fu">rep</span>(<span class="dv">5</span>,<span class="fu">nrow</span>(U_usm)),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method=</span><span class="st">'srswor'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co">#trato cada conglomerado (manzana) como un estrato y saco la muestra de 5  hogares en cada uno</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>s <span class="ot">=</span> <span class="fu">getdata</span>(U_usm,s) <span class="sc">%&gt;%</span> </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">prob_usm=</span>Prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br>
</p>
</section>
<section id="parte-4" class="level2">
<h2 class="anchored" data-anchor-id="parte-4">Parte 4</h2>
<p>Calcular la estimación puntual del ingreso promedio, proporción de hogares pobres y total de personas, a nivel de toda la población. Para cada estimación se debe computar: error estándar (SE), coeficiente de variación, efecto de diseño y márgenes de error al 95%.</p>
<p>Estimador Horvitz-Thompson en un diseño estratificado:</p>
<ul>
<li><p>Total: <span class="math inline">\(\hat{Y}_{HT}=\sum_{h=1}^H\sum_{i\in s}w_{hi}y_{hi}\)</span></p></li>
<li><p>Promedio: <span class="math inline">\(\hat{\bar{Y}}_{HT}=\frac{1}{N}\hat{Y}_{HT}=\frac{1}{N}\sum_{h=1}^H\sum_{i\in s_h}w_{hi}y_{hi}\)</span></p></li>
<li><p>Proporsión: <span class="math inline">\(\hat{\bar{Y}}_{HT}\)</span> con <em>y</em> una variable booleana.</p></li>
</ul>
<p><br>
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>s<span class="ot">=</span> s <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">prob_total=</span>prob_upm<span class="sc">*</span>prob_usm,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">w=</span><span class="dv">1</span><span class="sc">/</span>prob_total)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ps1<span class="ot">=</span> s <span class="sc">%&gt;%</span> <span class="fu">svydesign</span>(<span class="at">strata=</span><span class="sc">~</span> estrato , <span class="at">ids=</span><span class="sc">~</span>manzana<span class="sc">+</span>ID,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fpc=</span><span class="sc">~</span>prob_upm<span class="sc">+</span>prob_usm,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">weights=</span><span class="sc">~</span>w,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data=</span>.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Ingreso Promedio</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>ingreso_hog, ps1, <span class="at">deff =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>conf_int <span class="ot">&lt;-</span> <span class="fu">confint</span>(res)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>cv_res <span class="ot">&lt;-</span> <span class="fu">cv</span>(res)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>deff_res <span class="ot">&lt;-</span> <span class="fu">deff</span>(res)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  Estadística <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Ingreso promedio por hogar"</span>, <span class="st">"Límite inferior del IC"</span>, <span class="st">"Límite superior del IC"</span>, <span class="st">"Desvío"</span>, <span class="st">"Coeficiente de variación"</span>, <span class="st">"Efecto de diseño"</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">coef</span>(res), conf_int[<span class="dv">1</span>], conf_int[<span class="dv">2</span>], <span class="fu">SE</span>(res)[[<span class="dv">1</span>]], cv_res, deff_res), <span class="dv">3</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>resultados <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Estadística</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ingreso promedio por hogar</td>
<td style="text-align: right;">4646.796</td>
</tr>
<tr class="even">
<td style="text-align: left;">Límite inferior del IC</td>
<td style="text-align: right;">4534.264</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Límite superior del IC</td>
<td style="text-align: right;">4759.327</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desvío</td>
<td style="text-align: right;">57.415</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coeficiente de variación</td>
<td style="text-align: right;">0.012</td>
</tr>
<tr class="even">
<td style="text-align: left;">Efecto de diseño</td>
<td style="text-align: right;">1.435</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La media del ingreso de los hogares es de 4646.8, con desvío estándar de 57.4 un intervalo de confianza al 95% de <span class="math inline">\(\pm 122.5\)</span>. Considerando que esta variable toma valores entre 1287 y 60345 en la población, esta estimación es relativamente precisa.</p>
<p>El coeficiente de variación estimado, 0.012, explica que los valores que toma la variable, ingreso de los hogares, presentan una dispersión significativamente pequeña respecto a la media estimada, por lo que la misma resume bien a la variable.</p>
<p>Por otro lado, el efecto de diseño es mayor que 1; este resultado implica que el diseño utilizado es 1.4 veces menos eficiente que si se hubiera usado un diseño aleatorio simple (<em>MAS</em>).</p>
<p><br>
</p>
<p><strong>Hogares Pobres</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>pobre, ps1 , <span class="at">deff =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>conf_int <span class="ot">&lt;-</span> <span class="fu">confint</span>(res)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>cv_res <span class="ot">&lt;-</span> <span class="fu">cv</span>(res)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>deff_res <span class="ot">&lt;-</span> <span class="fu">deff</span>(res)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  Estadística <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Proporción de hogares pobres"</span>, <span class="st">"Límite inferior del IC"</span>, <span class="st">"Límite superior del IC"</span>, <span class="st">"Desvío"</span>, <span class="st">"Coeficiente de variación"</span>, <span class="st">"Efecto de diseño"</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">coef</span>(res), conf_int[<span class="dv">1</span>], conf_int[<span class="dv">2</span>], <span class="fu">SE</span>(res), cv_res, deff_res), <span class="dv">4</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>resultados <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Estadística</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Proporción de hogares pobres</td>
<td style="text-align: right;">0.0739</td>
</tr>
<tr class="even">
<td style="text-align: left;">Límite inferior del IC</td>
<td style="text-align: right;">0.0543</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Límite superior del IC</td>
<td style="text-align: right;">0.0935</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desvío</td>
<td style="text-align: right;">0.0100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coeficiente de variación</td>
<td style="text-align: right;">0.1352</td>
</tr>
<tr class="even">
<td style="text-align: left;">Efecto de diseño</td>
<td style="text-align: right;">2.3423</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Se estima que un 7.39% de la población son pobres, con un desvío de un 1% y, por consiguiente, con un <span class="math inline">\(IC_{95\%} = \pm 1.96\%\)</span>, lo cual permite pensar que esta es una estimación precisa.</p>
<p>Sin embargo, el coeficiente de variación estimado es de 0.135. Al ser bastante mayor que 0.03, podemos afirmar que los datos presentan gran dispersión, por lo que la proporción estimada no es representativa de los mismos.</p>
<p>En este caso, el efecto de diseño estimado permite observar que el diseño utlilizado es 2.3 veces más ineficiente que si se usar un <em>MAS</em> para estimar esta proporción.</p>
<p><br>
</p>
<p><strong>Total de Personas</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">svytotal</span>(<span class="sc">~</span>cant_personas, ps1, <span class="at">deff =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>conf_int <span class="ot">&lt;-</span> <span class="fu">confint</span>(res)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>cv_res <span class="ot">&lt;-</span> <span class="fu">cv</span>(res)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>deff_res <span class="ot">&lt;-</span> <span class="fu">deff</span>(res)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  Estadística <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Total de personas"</span>, <span class="st">"Límite inferior del IC"</span>, <span class="st">"Límite superior del IC"</span>, <span class="st">"Desvío"</span>, <span class="st">"Coeficiente de variación"</span>, <span class="st">"Factor de diseño"</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">coef</span>(res), conf_int[<span class="dv">1</span>], conf_int[<span class="dv">2</span>], <span class="fu">SE</span>(res), cv_res, deff_res), <span class="dv">3</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>resultados <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Estadística</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total de personas</td>
<td style="text-align: right;">1233250.294</td>
</tr>
<tr class="even">
<td style="text-align: left;">Límite inferior del IC</td>
<td style="text-align: right;">1204811.779</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Límite superior del IC</td>
<td style="text-align: right;">1261688.809</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desvío</td>
<td style="text-align: right;">14509.713</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coeficiente de variación</td>
<td style="text-align: right;">0.012</td>
</tr>
<tr class="even">
<td style="text-align: left;">Factor de diseño</td>
<td style="text-align: right;">0.783</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>El total de personas estimado es de 1.233 millones, con un desvío de 14509, con <span class="math inline">\(IC_{95\%} = \pm 28439\)</span>, lo cual parece ser una estimación suficientemente precisa.</p>
<p>El coeficiente de variación estimado es de 0.012, por lo que la variación de los datos despecto de su media es relativamente pequeña.</p>
<p>Por último, el efecto de diseño estimado es de 0.783, es decir que el diseño elegido es más eficiente que si se hubiera realizado un <em>MAS</em>.</p>
<p><br>
</p>
</section>
<section id="parte-5" class="level2">
<h2 class="anchored" data-anchor-id="parte-5">Parte 5</h2>
<p>La varianza a partir de la cual se calcula el desvío estándar (<span class="math inline">\(SE(\hat{\theta})=\sqrt{V(\hat{\theta})}\)</span>) de los parámetros a estimar en la parte anterior se obtiene por el <strong>método del último conglomerado</strong> de la siguiente manera:</p>
<p><span class="math display">\[\hat{V}_{UC}(\hat{\theta}) = \sum_{h=1}^{H}\frac{1}{m_h(m_h -1)}\sum_{j\in s_h}(\hat{\theta}^*_j m_{h} - \hat{\theta}_h)^2\]</span></p>
<p>donde <span class="math inline">\(\hat{\theta}^*_j\)</span> es la estimación del parámetro en la j-ésima UPM (manzana), <span class="math inline">\(\hat{\theta}_h\)</span> la estimación del parámetro para el h-ésimo estrato y <span class="math inline">\(m_h\)</span> la cantidad de UPMs del mismo estrato.</p>
<p><br>
</p>
</section>
<section id="parte-6" class="level2">
<h2 class="anchored" data-anchor-id="parte-6">Parte 6</h2>
<p>Calcular el ingreso per cápita en Montevideo (junto con su error estándar). Indique el tipo de parámetro y qué método fue utilizado por defecto por el paquete survey para la estimación del error estándar. Tenga en cuenta que el ingreso per cápita se calcula como: <span class="math inline">\(\frac{ingrsos \ totales \ en \ Montevideo}{Cantidad \ de \ habitantes}\)</span>.</p>
<p>Esta estimación es un ratio, por tanto se calcula como la razón entre dos totales, es decir <span class="math inline">\(R=\frac{Y}{Z}\)</span>, y se estima como <span class="math inline">\(\hat{R}=\frac{\hat{Y}_{HT}}{\hat{Z}_{HT}}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">svyratio</span>(<span class="sc">~</span>ingreso_hog, <span class="sc">~</span>cant_personas, ps1, <span class="at">deff =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>conf_int <span class="ot">&lt;-</span> <span class="fu">confint</span>(res)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>cv_res <span class="ot">&lt;-</span> <span class="fu">cv</span>(res)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>se_res <span class="ot">&lt;-</span> <span class="fu">SE</span>(res)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  Estadística <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Ingreso per cápita"</span>, <span class="st">"Límite inferior del IC"</span>, <span class="st">"Límite superior del IC"</span>, <span class="st">"Desvío"</span>, <span class="st">"Coeficiente de variación"</span>),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">coef</span>(res), conf_int[<span class="dv">1</span>], conf_int[<span class="dv">2</span>], se_res, cv_res), <span class="dv">4</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>resultados <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Estadística</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ingreso per cápita</td>
<td style="text-align: right;">1705.0376</td>
</tr>
<tr class="even">
<td style="text-align: left;">Límite inferior del IC</td>
<td style="text-align: right;">1647.0081</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Límite superior del IC</td>
<td style="text-align: right;">1763.0671</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desvío</td>
<td style="text-align: right;">29.6074</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coeficiente de variación</td>
<td style="text-align: right;">0.0174</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>El ingreso per cápita estimado en Montevideo es de 1705, con un desvío estándar estimado de 29.6 y un <span class="math inline">\(IC_{95\%} = \pm 58\)</span>. El coeficiente de variación estimado es de 0.017, por lo que la dispersión en los datos es relativamente pequeña.</p>
<p>Para este tipo de estimador, la varianza se calcula mediante el método de <strong>estimador de razón</strong> que aproxima pa varianza por linealización de Taylor. Entonces la varianza aproximada se calcula como:</p>
<p><span class="math display">\[AV(\hat{R})=V(\hat{R})=\frac{1}{Z^2}\sum_{i\in U}\sum_{i\in U}\triangle_{ij}\frac{y_i - Rz_i}{\pi_i}\frac{y_i - Rz_j}{\pi_j}\]</span></p>
<p>Y su estimación es: <span class="math inline">\(\hat{V}(\hat{R})=\frac{1}{\hat{Z}_{HT}^2}\sum_{i\in s}\sum_{i\in s}\frac{\triangle_{ij}}{\pi_{ij}}\frac{y_i - \hat{R}z_i}{\pi_i}\frac{y_i - \hat{R}z_j}{\pi_j}\)</span></p>
<p>Por último, el error estándar será <span class="math inline">\(SE(\hat{\theta})=\sqrt{V(\hat{\theta})}\)</span>.</p>
<p><br>
</p>
</section>
<section id="parte-7-y-8" class="level2">
<h2 class="anchored" data-anchor-id="parte-7-y-8">Parte 7 y 8</h2>
<p>Calcular la estimación del error estándar del punto anterior, utilizando dos métodos de remuestreo: Jackknife y Bootstrap (con 1000 réplicas). Compare los resultados obtenidos.</p>
<p><strong>Jackknife</strong></p>
<p>Este método de remuestreo se basa en eliminar una observación por réplica, es decir que hay tantas réplicas como observaciones. En el caso del diseño por conglomerados se elimina una UPM, por lo que los ponderadores se reescriben como: <span class="math inline">\(w_{hj(i)}= \frac{n_h}{n_h-1}w_{hj}\)</span>, donde <em>j</em> hace referencia a la UPM, <em>h</em> al estrato e <em>i</em> al índice de la réplica respectiva.</p>
<p>Un total en cada réplica se calcula entonces como <span class="math inline">\(\hat{Y}_{(i)}=\sum_{j\in s_{(i)}}w_{j(i)}y_j\)</span>. Y el ratio respectivo es <span class="math inline">\(\hat{R}_{(i)}=\frac{\hat{Y}_{(i)}}{\hat{Z}_{(i)}}\)</span>.</p>
<p>La varianza de un estimador en este método se calcula como: <span class="math inline">\(V_J(\hat{Y})=\frac{n_I}{n_I-1}\sum_{i=1}^{n_I}(\hat{Y}_{(i)}-\hat{Y})^2\)</span>. Aplicando esta fórmula a las enstimaciones del ratio de interés y calculando su raíz cuadrada, obtenemos el error estándar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pps1 <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">strata =</span> <span class="sc">~</span>estrato,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">ids =</span> <span class="sc">~</span>manzana <span class="sc">+</span> ID,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs  =</span> <span class="sc">~</span>prob_upm <span class="sc">+</span> prob_usm ,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> s  </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>jkn <span class="ot">&lt;-</span> <span class="fu">as.svrepdesign</span>(<span class="at">design =</span> pps1, <span class="at">type =</span> <span class="st">"JKn"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>te<span class="ot">=</span><span class="fu">svyratio</span>(<span class="sc">~</span>ingreso_hog, <span class="sc">~</span>cant_personas, jkn , <span class="at">return.replicates=</span><span class="cn">TRUE</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>estimacion <span class="ot">&lt;-</span> te<span class="sc">$</span>ratio</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>desvio <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(te<span class="sc">$</span>var)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  Estimación <span class="ot">=</span> estimacion[<span class="dv">1</span>],</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  Desvío <span class="ot">=</span> desvio</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>resultados <span class="sc">%&gt;%</span>  <span class="fu">round</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Estimación</th>
<th style="text-align: right;">Desvío</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1705.04</td>
<td style="text-align: right;">28.72</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La estimaciones del ingreso per cápita y su error estándar por el método de <em>Jackknife</em> es aproximadamente igual a las etimaciones por el método de <em>estimador de razón</em>.</p>
<p><br>
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">est=</span> te<span class="sc">$</span>replicates) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>()<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>est), <span class="at">bins=</span><span class="dv">20</span>, <span class="at">fill=</span><span class="st">'purple'</span>, <span class="at">color=</span><span class="st">'white'</span>)<span class="sc">+</span><span class="fu">theme_light</span>()<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">"Réplicas ingreso per cápita"</span>)<span class="sc">+</span><span class="fu">ggtitle</span>(<span class="st">"Distribución de las réplicas del ingreso per cápita estimado por Jkn"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="muestreo_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Según el método Jackkife, las estimaciónes en las réplicas del ingreso per cápita parecen estar más concentradas en valores en torno a 1705, con una distribución asimétirca hacia valores bajos.</p>
<p><br>
</p>
<p><strong>Bootstrap</strong></p>
<p>Para este diseño, el cual presenta estratos, usaremos la variación del método Bootstrap, Rao-Wu. La misma consiste en extraer, en este caso, 1000 muestras aleatorias simples con reposición (réplicas) de tamaño <span class="math inline">\(m'_h\)</span> de las UPM entre las <span class="math inline">\(m_h\)</span> seleccionadas en la muestra original.</p>
<p>Sea <span class="math inline">\(m^b_{hj}\)</span> la cantidad de veces que aparece la j-ésima UPM es seleccionada en la réplica b, el <em>factor de multiplicidad</em>. Entonces el ponderador a utilizar será: <span class="math inline">\(w^b_{khj}=\frac{m_h}{m_h - 1}w_{khj}\)</span>.</p>
<p>A partir de esto se calculan para cada réplica los totales pertinentes por el método de Horvitz-Thompson y con ellos el ratio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|output=FALSE</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>boot<span class="ot">=</span><span class="fu">as.svrepdesign</span>(<span class="at">design=</span>ps1, <span class="at">type=</span><span class="st">'subbootstrap'</span>, <span class="at">replicates=</span><span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>te<span class="ot">=</span><span class="fu">svyratio</span>(<span class="sc">~</span>ingreso_hog, <span class="sc">~</span>cant_personas, boot,<span class="at">return.replicates=</span><span class="cn">TRUE</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>estimacion <span class="ot">&lt;-</span> te<span class="sc">$</span>ratio</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>desvio <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(te<span class="sc">$</span>var)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  Estimación <span class="ot">=</span> estimacion[<span class="dv">1</span>],</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  Desvío <span class="ot">=</span> desvio</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>resultados <span class="sc">%&gt;%</span>  <span class="fu">round</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Estimación</th>
<th style="text-align: right;">Desvío</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1705.04</td>
<td style="text-align: right;">29.14</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La estimaciones del ingreso per cápita y su error estándar por el método de <em>Bootstrap</em> es aproximadamente igual a las etimaciones por los métodos de <em>estimador de razón</em> y <em>Kackknife</em>.</p>
<p><br>
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">est=</span> te<span class="sc">$</span>replicates) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>()<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>est), <span class="at">bins=</span><span class="dv">20</span>, <span class="at">fill=</span><span class="st">'purple'</span>, <span class="at">color=</span><span class="st">'white'</span>)<span class="sc">+</span><span class="fu">theme_light</span>()<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">"Réplicas ingreso per cápita"</span>)<span class="sc">+</span><span class="fu">ggtitle</span>(<span class="st">"Distribución de las réplicas del ingreso per cápita estimado por Rao-Wu"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="muestreo_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Según el método de Bootstrap, las estimaciónes en las réplicas de la variable, ingreso per cápita, tienden a concentrarse en valores en torno a 1700, con una distribución aproximadamente simétrica.</p>
<p><br>
</p>
</section>
<section id="parte-9" class="level2">
<h2 class="anchored" data-anchor-id="parte-9">Parte 9</h2>
<p>Estimar la cantidad de personas pobres y no pobres (junto con sus márgenes de error). Indicar si los dominios de estimación son planeados o no planeados. Para este caso, utilices el Bootstrap realizado en los puntos anteriores. Comente los resultados obtenidos y proponga estrategias para mejorar la precisión de las estimación obtenida.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># res_pobre &lt;- svytotal(~pobre, boot)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># conf_int_pobre &lt;- confint(res_pobre)</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># se_pobre &lt;- SE(res_pobre)</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>res_no <span class="ot">&lt;-</span> <span class="fu">svytotal</span>(<span class="sc">~</span>(pobre<span class="sc">==</span><span class="dv">0</span>), boot)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>conf_int_no <span class="ot">&lt;-</span> <span class="fu">confint</span>(res_no)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>se_no <span class="ot">&lt;-</span> <span class="fu">SE</span>(res_no)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un data frame para los resultados</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>resultados_pobre <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estado =</span> <span class="fu">c</span>(<span class="st">"Personas pobres"</span>, <span class="st">"Personas no pobres"</span>),</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  Estimación <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">coef</span>(res_no), <span class="dv">0</span>),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Límite inferior IC</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(conf_int_no[, <span class="dv">1</span>], <span class="dv">0</span>),</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Límite superior IC</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(conf_int_no[, <span class="dv">2</span>], <span class="dv">0</span>),</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Error estándar</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(se_no, <span class="dv">0</span>))</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(resultados_pobre) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>resultados_pobre <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estado</th>
<th style="text-align: right;">Estimación</th>
<th style="text-align: right;">Límite.inferior.IC</th>
<th style="text-align: right;">Límite.superior.IC</th>
<th style="text-align: right;">Error.estándar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Personas pobres</td>
<td style="text-align: right;">33444</td>
<td style="text-align: right;">24911</td>
<td style="text-align: right;">41977</td>
<td style="text-align: right;">4354</td>
</tr>
<tr class="even">
<td style="text-align: left;">Personas no pobres</td>
<td style="text-align: right;">419070</td>
<td style="text-align: right;">402946</td>
<td style="text-align: right;">435193</td>
<td style="text-align: right;">8227</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Se estima que en la población hay <span class="math inline">\(33444\pm 8533\)</span> personas pobres contra <span class="math inline">\(419070 \pm 16123\)</span> no pobres (siendo el intervalo de confianza al 95%), con errores estándar estimados de 4354 y 8227, respectivamente. La precisión de la estimación del total de no pobres es relativamente alta, pero la de pobres presenta una dispersión grande en comparación con su valor estimado.</p>
<p>Los dominios de estimación en este caso son no planeados, ya que como no se conoce a priori el factor de multiplicidad de las UPMs, tampoco se puede conocer ni controlar el tamaño de muestra, algunas UPMs de la muestra original podrían no estar en las réplicas y otras estarán repetidas.</p>
<p>Si se quisieran mejorar dichas estimaciones se podría estratificar también según si son o no pobres, o en el caso de hacer conglomerados por manzanas, si la proporción de pobres en dicha manzana pasa o no cierto umbral; asignar el tamaño de muestra por estratos según una variable que se encuentre más relacionada con la variable de pobreza; usar un tamaño de muestra mayor; como alguos ejemplos.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>